export const EVENT_ALL = 'ALL';
export const EVENT_GO_LIVE = 'GO_LIVE';
export const EVENT_GO_OFFLINE = 'GO_OFFLINE';
export const EVENT_GO_LIVE_AGAIN = 'GO_LIVE_AGAIN';
export const EVENT_CHANNEL_NOT_FOUND = 'NOT_FOUND';
export const EVENT_BROADCAST_ADD = 'BROADCAST_ADD';
export const EVENT_BROADCAST_CHANGE = 'BROADCAST_CHANGE';
export const EVENT_BROADCAST_REMOVE = 'BROADCAST_REMOVE';
