module.exports = {
    EVENT_ALL: 'ALL',
    EVENT_GO_LIVE: 'GO_LIVE',
    EVENT_GO_OFFLINE: 'GO_OFFLINE',
    EVENT_CHANNEL_NOT_FOUND: 'NOT_FOUND',
    EVENT_BROADCAST_ADD: 'BROADCAST_ADD',
    EVENT_BROADCAST_CHANGE: 'BROADCAST_CHANGE',
    EVENT_BROADCAST_REMOVE: 'BROADCAST_REMOVE',
};
